[package]
name = "rescrobbled"
version = "0.3.2"
authors = ["Koen Bolhuis <koen.bolhuis@gmail.com>"]
edition = "2018"

[dependencies]
mpris = "2.0.0-rc2"
rustfm-scrobble = "1"
listenbrainz-rust = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
dirs = "3"
notify-rust = "4"

[dev-dependencies]
tempfile = "3"
