[package]
name = "rescrobbled"
version = "0.7.2"
authors = ["Koen Bolhuis <koen.bolhuis@gmail.com>"]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/InputUsername/rescrobbled.git"
homepage = "https://github.com/InputUsername/rescrobbled"
readme = "README.md"
description = "MPRIS music scrobbler daemon"
keywords = ["mpris", "music", "scrobble", "daemon"]
categories = ["multimedia", "command-line-utilities"]
publish = false

[dependencies]
mpris = "2.0.1"
rustfm-scrobble-proxy = "2.0.0"
listenbrainz = "0.8.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
dirs = "6.0.0"
anyhow = "1.0.98"
rpassword = "7.4.0"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tempfile = "3.20.0"
